### PR TITLE
AWS System Get includes Region and Account ID

### LINKED ISSUE #58: Region in SystemGet()
It would be nice to introspect a rack's region via the SystemGet API

### PR DESCRIPTION
**Pull request by nzoschke**
Fixes #58

### CODE REVIEW

**Comment by ddollar** [comment]
`AccountID` should just be `Account`

This smells a bit AWS-specific. What will the local rack return for Account?

**Comment by nzoschke** [comment]
Verified working

```
$ curl -k https://781086b006c664fd71b6583f96e2fc95:@rack.test2-Balan-1I65GUIL3WH4-249833466.us-east-1.rack.convox.io/system | jq
{
  "account_id": "132866487567",
  "domain": "test2-Balan-1I65GUIL3WH4-249833466.us-east-1.rack.convox.io",
  "name": "test2",
  "image": "convox/praxis:noah",
  "region": "us-east-1",
  "version": "noah"
}
```

**Comment by nzoschke** [comment]
Definitely AWS specific at the moment.

But I think it will apply to any cloud provider. It's useful to know the remote account id for all integrations.

**Comment by nzoschke** [comment]
updated for `Account`

**Pull request merged**
