### PR TITLE
app delete confirmation

### PR DESCRIPTION
**Pull request by MiguelMoll**
```
> cx apps delete ph2
Rack  otherstuff/px
App   ph2
Delete the app? y/N: y
deleting ph2: OK
```

### CODE REVIEW

**Comment by MiguelMoll** [comment]
[cx apps delete should confirm org, rack, and app name](https://trello.com/c/dQbLqd9H/2654-cx-apps-delete-should-confirm-org-rack-and-app-name)

**Comment by nzoschke** [comment]
A common pattern for confirmation is to type the whole name. See Heroku and the S3 web console.

```
$ cx apps delete myapp
Are you sure? Type 'myorg/staging/myapp' to confirm.
> foo
Delete cancelled.

$ cx apps delete myapp
Are you sure? Type 'myorg/staging/myapp' to confirm.
> myorg/staging/myapp
deleting ph2: OK
```

**Comment by MiguelMoll** [comment]
I get the following when entering the wrong app name:
```
cx apps delete foobar
Are you sure? Type otherstuff/px/foobar to confirm:
> otherstuff/px/foobar
deleting otherstuff/px/foobar: ERROR: no such app: foobar
```
Should work the same way if logged in via RACK_URL or the console proxy.

**Comment by mattmanning** [comment]
Looks like that only pops up if you do some extra nesting that isn't valid:

```
$  ./cx apps delete local/foobar
Are you sure? Type local/local/foobar to confirm:
> local/local/foobar
deleting local/local/foobar: ERROR: response status 404
```

**Pull request merged**
